import React, { useState } from "react";
import {
  Document,
  Page,
  Text,
  
  StyleSheet,
  Image,
  pdf,
} from "@react-pdf/renderer";
import { registerInvestor } from "../../api/Service/investor.api";
import { type SignUpRequest } from "../../Types/SignUpRequest";
import Toast, { type ToastType } from "../../utils/Toast";
import { useNavigate } from "react-router-dom";
import "../../Styles/SignUp/FinalVerification.css";

const pdfStyles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: "Helvetica",
    color: "#111",
    lineHeight: 1.5,
  },
  title: {
    fontSize: 18,
    textAlign: "center",
    marginBottom: 10,
    color: "#17203d",
    fontWeight: "bold",
  },
  sectionTitle: {
    fontSize: 14,
    marginVertical: 10,
    color: "#17203d",
    fontWeight: "bold",
  },
  text: { marginBottom: 4 },
  image: {
    width: 120,
    height: 120,
    borderRadius: 8,
    position: "absolute",
    right: 40,
    top: 80,
  },
  signature: {
    width: 180,
    height: 60,
    marginTop: 20,
    alignSelf: "center",
  },
  footer: {
    position: "absolute",
    bottom: 40,
    left: 40,
    fontSize: 10,
    color: "#555",
  },
});

interface Props {
  form: SignUpRequest;
  setForm: React.Dispatch<React.SetStateAction<SignUpRequest>>;
}

const FinalVerification: React.FC<Props> = ({ form, setForm }) => {
  const [pdfBlob, setPdfBlob] = useState<Blob | null>(null);
  const [toast, setToast] = useState<{ message: string; type: ToastType } | null>(
    null
  );
  const navigate = useNavigate();
  const showToast = (message: string, type: ToastType) =>
    setToast({ message, type });


  const fileToBase64 = (file: File): Promise<string> =>
    new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });


  const InvestmentAgreementPDF = ({
    investor,
    image,
    signature,
  }: {
    investor: SignUpRequest;
    image?: string;
    signature?: string;
  }) => (
    <Document>
      {/* PAGE 1: INVESTOR INFO */}
      <Page size="A4" style={pdfStyles.page}>
        <Text style={pdfStyles.title}>Investment Agreement Document</Text>
        <Text style={{ textAlign: "center", marginBottom: 10 }}>
          Generated by Investment Plan System
        </Text>

        {image && <Image src={image} style={pdfStyles.image} />}

        <Text style={pdfStyles.sectionTitle}>Investor Details</Text>
        <Text style={pdfStyles.text}>Name: {investor.investorName}</Text>
        <Text style={pdfStyles.text}>Email: {investor.email}</Text>
        <Text style={pdfStyles.text}>Mobile: {investor.mobile}</Text>
        <Text style={pdfStyles.text}>Aadhaar No: {investor.aadhaarNo}</Text>
        <Text style={pdfStyles.text}>PAN No: {investor.panNo}</Text>
        <Text style={pdfStyles.text}>Bank Name: {investor.bankName}</Text>
        <Text style={pdfStyles.text}>
          Initial Fund Added: ₹{investor.fund}
        </Text>
         <Text style={pdfStyles.text}>Nominee Name: {investor.nomineeName}</Text>
        <Text style={pdfStyles.text}>Nominee Email: {investor.nomineeEmail}</Text>
        <Text style={pdfStyles.text}>Nominee Relation: {investor.nomineeRelation}</Text>

        <Text style={pdfStyles.sectionTitle}>Agreement Overview</Text>
        <Text>
          This Investment Agreement outlines the responsibilities, liabilities,
          and mutual commitments between the investor and the Investment Plan
          platform. The investor agrees to provide accurate personal and
          financial details for verification and acknowledges the inherent risks
          associated with financial markets.
        </Text>

        <Text style={{ marginTop: 8 }}>
          The company ensures the safety and confidentiality of user data,
          following the regulatory framework under SEBI and RBI guidelines. All
          transactions will be executed via authorized financial institutions
          with full transparency.
        </Text>

        <Text style={pdfStyles.footer}>
          Date of Agreement: {new Date().toLocaleDateString()}
        </Text>
      </Page>

   
      <Page size="A4" style={pdfStyles.page}>
        <Text style={pdfStyles.sectionTitle}>
          Investment Terms & Conditions
        </Text>
        <Text>
          1. KYC verification is mandatory before any investment activity.{"\n"}
          2. Investor must maintain sufficient funds for SIP or lump-sum
          investments.{"\n"}
          3. The platform reserves the right to modify fund allocation strategy
          under market conditions.{"\n"}
          4. All communications regarding transactions will be sent via
          registered email.{"\n"}
          5. Withdrawals (redemption) are subject to SEBI-regulated lock-in
          periods.{"\n"}
          6. The investor acknowledges that investment values may fluctuate
          based on market trends.{"\n"}
          7. The digital signature at the end of this document represents
          investor consent.{"\n"}
          8. Income proof, PAN, and Aadhaar are mandatory for regulatory
          compliance.
        </Text>
      </Page>

    
      <Page size="A4" style={pdfStyles.page}>
        <Text style={pdfStyles.sectionTitle}>
          Regulatory & Compliance Statement
        </Text>
        <Text>
          Our system is registered under SEBI norms and operates under AML
          (Anti-Money Laundering) and PMLA (Prevention of Money Laundering Act)
          compliance. The investor must ensure that no fraudulent or unlawful
          activity is performed through the platform. All financial data is
          securely stored and encrypted using RSA and AES algorithms.
        </Text>
      </Page>

      <Page size="A4" style={pdfStyles.page}>
        <Text style={pdfStyles.sectionTitle}>Acknowledgement & Signature</Text>
        <Text>
          By signing this agreement, the investor acknowledges having read and
          understood the policies, terms, and risks associated with investments
          in mutual funds, equities, or digital assets through the platform.
        </Text>

        {signature && <Image src={signature} style={pdfStyles.signature} />}
        <Text style={{ textAlign: "center", marginTop: 5 }}>
          Authorized Digital Signature
        </Text>

        <Text style={pdfStyles.footer}>
          Investor ID will be assigned post-verification.
        </Text>
      </Page>
    </Document>
  );


  const generatePDF = async () => {
    try {
      const investorImage = form.investorImage
        ? await fileToBase64(form.investorImage)
        : undefined;
      const investorSignature = form.signature
        ? await fileToBase64(form.signature)
        : undefined;

      const doc = (
        <InvestmentAgreementPDF
          investor={form}
          image={investorImage}
          signature={investorSignature}
        />
      );

      const blob = await pdf(doc).toBlob();
      setPdfBlob(blob);

      const file = new File([blob], "Investment_Agreement.pdf", {
        type: "application/pdf",
      });
      setForm((prev) => ({ ...prev, signedDocument: file }));
      showToast(" Signed document generated successfully", "success");
    } catch (error) {
      console.error(error);
      showToast("Error generating PDF", "error");
    }
  };

  const viewPDF = () => {
    if (!pdfBlob) return showToast("Please generate PDF first", "error");
    const url = URL.createObjectURL(pdfBlob);
    window.open(url);
  };


  const downloadPDF = () => {
    if (!pdfBlob) return showToast("Please generate PDF first", "error");
    const url = URL.createObjectURL(pdfBlob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "Investment_Agreement.pdf";
    a.click();
  };

  
  const handleSignUp = async () => {
    try {
      const required = [
        "investorName",
        "email",
        "password",
        "mobile",
        "aadhaarNo",
        "panNo",
        "bankName",
        "fund",
        "investorImage",
        "signature",
        "incomeProof",
        "signedDocument",
      ];

      for (const key of required) {
        if (!form[key as keyof SignUpRequest]) {
          showToast(`Please provide ${key}`, "error");
          return;
        }
      }

      const formData = new FormData();
      Object.entries(form).forEach(([key, value]) => {
        if (value instanceof File) formData.append(key, value);
        else formData.append(key, String(value ?? ""));
      });

      const res = await registerInvestor(formData);
      if (res.success) {
        showToast(res.message, "success");
        setTimeout(() => navigate("/login"), 300);
      } else {
        showToast(res.message || "Registration failed", "error");
      }
    } catch (err) {
      console.error("Error during registration:", err);
      showToast("Error registering investor", "error");
    }
  };
  return (
    <div className="verify">
    <div className="final-verification-container">
      <h2 className="final-verification-title">🎯 Final Verification</h2>
      <p className="final-verification-subtitle">
        Congratulations, <b>{form.investorName}</b>! Your KYC and payment have
        been verified. Please generate your signed investment agreement below.
      </p>

      <div className="final-btn-group">
        {!pdfBlob ? (
          <button onClick={generatePDF} className="final-btn primary">
            🖋 Generate Signed Document
          </button>
        ) : (
          <>
            <button onClick={viewPDF} className="final-btn view">
              View Signed Document
            </button>
            <button onClick={downloadPDF} className="final-btn download">
              Download Signed Document
            </button>
            <button onClick={handleSignUp} className="final-btn complete">
              Complete Sign Up
            </button>
          </>
        )}
      </div>

      {toast && (
        <Toast message={toast.message} type={toast.type} onClose={() => setToast(null)} />
      )}
    </div>
    </div>
  );
};

export default FinalVerification;
